version: "2"
run:
  timeout: 2m
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - gosec
    - intrange
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
